#!/bin/bash -e


script_dir=$(dirname "$0")
source ${script_dir}/setup

CONTOUR_HELM_VERSION=${CONTOUR_HELM_VERSION:-v7.9.2}
CONTOUR_VERSION=${CONTOUR_VERSION:-v1.21.0}

exit_code=0
helm status contour &>/dev/null || exit_code=$?
if [[ $exit_code == 0 ]]; then
    exit 0;
fi

echo "Updating bitnami helm chart repository"
helm repo add bitnami https://charts.bitnami.com/bitnami 1>/dev/null
helm repo update bitnami 1>/dev/null

install_flags=""
if [[ ${CONTOUR_DEBUG} != false ]]; then
    install_flags="--debug"
fi

echo "Installing bitnami/contour helm chart"
helm install contour bitnami/contour \
    ${install_flags} \
    --version "${CONTOUR_HELM_VERSION#v}" \
    --kube-context "${BOOTSTRAP_CONTEXT}" \
    --create-namespace --namespace "${CONTOUR_NAMESPACE}" \
    --set "contour.image.tag=${CONTOUR_VERSION}" \
    --values "${script_dir}/values.yaml" \
    --wait

echo "Installed bitnami/contour helm chart"