#!/bin/bash -e

CONTOUR_DEBUG=${CONTOUR_DEBUG:-false}

if [[ ${CONTOUR_DEBUG} != false ]]; then
    set -x
fi

SCRIPT_DIR=$(dirname "$0")

if [[ -z ${BOOTSTRAP_CONTEXT} ]]; then
    echo "BOOTSTRAP_CONTEXT is required" >&2
    exit 1;
fi

CONTOUR_VERSION=${CONTOUR_VERSION:-v7.8.0}
CONTOUR_NAMESPACE=${CONTOUR_NAMESPACE:-ingress}

helm -n ${CONTOUR_NAMESPACE} status contour &>/dev/null || exit_code=$?
if [[ $exit_code -eq 0 ]]; then
    exit 0;
fi

echo "Updating bitnami helm chart repository"
helm repo add bitnami https://charts.bitnami.com/bitnami 1>/dev/null
helm repo update bitnami 1>/dev/null

install_flags=""
if [[ ${CONTOUR_DEBUG} != false ]]; then
    install_flags="--debug"
fi

echo "Installing bitnami/contour helm chart"
helm install contour bitnami/contour \
    ${install_flags} \
    --version "${CONTOUR_VERSION#v}" \
    --kube-context "${BOOTSTRAP_CONTEXT}" \
    --create-namespace --namespace "${CONTOUR_NAMESPACE}" \
    --values "${SCRIPT_DIR}/values.yaml" \
    --wait

echo "Installed bitnami/contour helm chart"