#!/bin/bash -ex

CONTOUR_VERSION=${CONTOUR_VERSION:-v1.20.0}

helm -n ingress status contour &>/dev/null || exit_code=$?
if [[ $exit_code -eq 0 ]]; then
    exit 0;
fi

kubectl kustomize github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.4.1 | \
    kubectl --context ${BOOTSTRAP_CONTEXT} apply -f -

helm repo add bitnami https://charts.bitnami.com/bitnami

helm install contour bitnami/contour \
    --kube-context ${BOOTSTRAP_CONTEXT} \
    --create-namespace --namespace ingress \
    --set contour.image.registry=ghcr.io \
    --set contour.image.repository=projectcontour/contour \
    --set contour.image.tag=${CONTOUR_VERSION}